name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gbx-archive/backend:latest .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/gbx-archive/backend:latest

      - name: Clean up
        run: |
          docker logout
          rm -rf node_modules

  deploy:
    needs: build  # Ensure the build job completes before deploying
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      - name: SSH into the server and deploy
        run: |
          ssh -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker pull ghcr.io/gbx-archive/backend:latest'
          ssh -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker stop gbx-archive-backend || true'
          ssh -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker rm gbx-archive-backend || true'
          ssh -i ssh_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker run -d --name gbx-archive-backend -p 8080:8080 --env-file /home/data/gbxa-backend.env ghcr.io/gbx-archive/backend:latest'

      - name: Clean up SSH key
        run: |
          ssh-agent -k
          rm -f ssh_key