name: Build & Deploy for Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for ARM
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -t ghcr.io/gbx-archive/backend:latest -f docker/Dockerfile .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/gbx-archive/backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker pull ghcr.io/gbx-archive/backend:latest'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker stop gbx-archive-backend || true'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker rm gbx-archive-backend || true'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker run -d --name gbx-archive-backend -p 8080:8080 --env-file /home/data/gbxa-backend.env ghcr.io/gbx-archive/backend:latest'

      - name: Clean up SSH key
        run: |
          ssh-agent -k
